### ISSUE TITLE
Server unable to start after pod restart with Infinispan 15

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-helm-charts#119]
Infinispan 15 introduced the  [unclean-shutdown-action](https://github.com/infinispan/infinispan-operator/issues/1997) configuration on the global state. The new default behaviour blocks server startup in the event of a dangling global state lock file, which is always present when a pod is killed ungracefully e.g. restarted after an OOM.

To fix this issue we need to configure the the 15.0.x servers to use the IGNORE strategy which will ignore the dangling lock file and load the previous global state:

```yaml
  infinispan:
    cacheContainer:
      name: default
      globalState:
        uncleanShutdownAction: IGNORE
```
