### ISSUE TITLE
Expose Infinispan configuration in .Values

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-helm-charts#14]
Infinispan 13.0 allows the server and logging to be configured via yaml. Instead of utilising the `_infinispan.xml` and `_log4j2.xml` templates, we can embed the default configurations in the `values.yaml`.

The advantage of this approach is that it's now possible to update the configurations at chart creation time without having to modify any templates. This is necessary in order to better integrate with the Openshift Helm charts UI.

For example, `values.yaml` could like the following:

```yaml
images:
  server: 'registry.redhat.io/datagrid/datagrid-8-rhel8:1.2'
  initContainer: registry.access.redhat.com/ubi8-micro
deploy:
  replicas: 1
  ...
  infinispan:
    cache-container:
      ...
    server:
```

A consequence of this approach is that it's no longer possible to support the toggling of authentication (`values.security.authentication: true | false`) as template logic is not allowed in `values.yaml`.
