### ISSUE TITLE
Generated authentication secret is removed on upgrade

### ISSUE THREAD

**Issue by alvarolop** [infinispan/infinispan-helm-charts#34]
I think that this is partially covered by #25. 

With the current latest version, defining a configuration as:
```yaml
#Build configuration
images:
  server: quay.io/infinispan/server:13.0
  initContainer: registry.access.redhat.com/ubi8-micro
#Deployment configuration
deploy:
  replicas: 1
```
And creating the cluster with
```bash 
helm install infinispan openshift-helm-charts/infinispan-infinispan -f rhdg-chart/minimal-values.yaml
```

When I try to update the cluster to have to replicas, the secret is gone and Helm cannot create the second pod:
```bash
helm upgrade infinispan openshift-helm-charts/infinispan-infinispan -f rhdg-chart/minimal-values.yaml --set deploy.replicas=2
```

If this is fully duplicated, please close this case.
