### ISSUE TITLE
duplicated mapping key for clusterName

### ISSUE THREAD

**Issue by ehsan-tashkhisi** [infinispan/infinispan-helm-charts#61]
In some resources, `infinispan-helm-charts.labels` template is used to set the labels, this template contains `clusterName` itself but still `clusterName` is set individually for some resources and hence there are duplicated keys for `clusterName`, there is no problem when installing with helm but when I use skaffold which run some post-render process in helm and validate the YAML format, it throws an error.

The generated output in helm is:

```
apiVersion: v1
kind: Service
metadata:
  name: infinispan-metrics
  annotations:
    meta.helm.sh/release-name: 
    meta.helm.sh/release-namespace: default
  labels:
    app: infinispan-service-metrics
    clusterName: infinispan
    clusterName: infinispan
    helm.sh/chart: infinispan-0.3.0
    meta.helm.sh/release-name: infinispan
    meta.helm.sh/release-namespace: default
    app.kubernetes.io/version: "14.0"
```

Here is the error I get in skaffold
```
Error: INSTALLATION FAILED: error while running post render on files: error while running command /Users/tashkhisi/.asdf/installs/skaffold/2.0.1/bin/skaffold. error output:
reading Kubernetes YAML: yaml: unmarshal errors:
  line 12: mapping key "clusterName" already defined at line 11

```
