### ISSUE TITLE
Unable to set custom env or secrets

### ISSUE THREAD

**Issue by gdsmith** [infinispan/infinispan-helm-charts#76]
It's a common use case to be able to set custom env values for a deployment/stateful set but it doesn't seem like that is possible with this helm chart.

Would you accept a PR for changes to enable that? From both a list defined in the chart and from a secret. If you would, can you advise if there is a preferred format for that?

Use case for adding env to values.yaml config eg:

```yaml
deploy:
  container:
    envFromSecrets:
     - "mySecretNameContainingPostGresPassword"
    env:
      POSTGRES_URL: jdbc:postgresql://infinispan-postgres:5432/infinispan
      POSTGRES_USERNAME: infinispan

  # the infinispan config
  infinispan:
    cacheContainer:
      statistics: true
      caches:
        myTemplate:
          distributedCacheConfiguration:
            owners: ${env.STANDARD_OWNERS:2}
        myCacheName:
          distributedCache:
            configuration: myTemplate
      server:
        dataSources:
          - name: ds
            jndiName: 'jdbc/postgres'
            statistics: true
            connectionFactory:
              driver: org.postgresql.Driver
              url: '${env.POSTGRES_URL:jdbc:postgresql://infinispan-postgres:5432/infinispan}'
              username: '${env.POSTGRES_USERNAME:postgres}'
              password: '${env.POSTGRES_PASSWORD:mysecretpassword}'
```

We can then override the env for different environments with our own custom settings rather than having to update values throughout the charts.

**Comment by ryanemerson** [comment]
> Would you accept a PR for changes to enable that? From both a list defined in the chart and from a secret. If you would, can you advise if there is a preferred format for that?

PRs are always welcome :slightly_smiling_face:

I would suggest that we use the same format as the kubernetes pod spec for .env e.g.:

```yaml
deploy:
  container:
    env:
    - name: POSTGRES_URL
      value: jdbc:postgresql://infinispan-postgres:5432/infinispan
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mySecretNameContainingPostGresPassword
          key: password
    - name: CONFIG_MAP_EXAMPLE
      valueFrom:
        configMapKeyRef:
          name: example-config-map
          key: some-useful-key-value
```

Utilising ^ we're consistent with the Kubernetes API and we also have support for loading values from ConfigMaps.
