### ISSUE TITLE
any possibility to include a cache .json with a schema during pod launch?

### ISSUE THREAD

**Issue by makdeniss** [infinispan/infinispan-helm-charts#84]
So I have a quarkus pod that is starting after my infinispan pod is successfully up.
I would like infinispan to have a specific cache schema already in place when its created / restarted / whatever.
Is there a property in chart I can use to supply a json structure / file to do this?

**Comment by ryanemerson** [comment]
@makdeniss By Cache schema do you mean a cache instance, e.g. distributed-cache, replicated-cache, that will be available on server startup?

If so, it's possible to define these in the `values.yaml` under `deploy.infinispan`. For example:
```yaml
deploy:
  ...
  infinispan:
    cacheContainer:
      # [USER] Add cache, template, and counter configuration.
      name: default
      # [USER] Specify `security: null` to disable security authorization.
      security:
        authorization: {}
      transport:
        cluster: ${infinispan.cluster.name:cluster}
        node-name: ${infinispan.node.name:}
        stack: kubernetes
      # Define one or more caches
      caches:
        mycacheone:
          distributedCache:
            mode: "ASYNC"
        mycachetwo:
          distributedCache:
            mode: "SYNC"
    server:
      ...
````
