### ISSUE TITLE
how to enable global statistics with helm chart? 

### ISSUE THREAD

**Issue by altfatterz** [infinispan/infinispan-helm-charts#86]
I have the following values.yaml which defines a cache template `default`. On startup of the different services I create caches based on this template.  

I am wondering why on the console however global statistics is not enabled. 

Do you know how can I enable it with yaml definition?

```yaml
images:
  server: quay.io/infinispan/server:14.0
  initContainer: registry.access.redhat.com/ubi8-micro
deploy:
  replicas: 3
  container:
    storage:
      ephemeral: true
  infinispan:
    cacheContainer:
      distributedCacheConfiguration:
        name: default
        mode: ASYNC
        statistics: true
        expiration:
          lifespan: 300000
          maxIdle: 120000
        memory:
          maxCount: 1000
          whenFull: REMOVE
```

<img width="1294" alt="Screenshot 2023-09-18 at 15 32 17" src="https://github.com/infinispan/infinispan-helm-charts/assets/1025546/47f58ac9-63ac-470f-89cc-78fadc571b86">

**Comment by ryanemerson** [comment]
@altfatterz You need to enable statistics at the `cacheContainer` level, so your yaml needs to be updated to the following:

```yaml
images:
  server: quay.io/infinispan/server:14.0
  initContainer: registry.access.redhat.com/ubi8-micro
deploy:
  replicas: 3
  container:
    storage:
      ephemeral: true
  infinispan:
    cacheContainer:
      statistics: true # Global statistics
      distributedCacheConfiguration:
        name: default
        mode: ASYNC
        statistics: true # Cache statistics
        expiration:
          lifespan: 300000
          maxIdle: 120000
        memory:
          maxCount: 1000
          whenFull: REMOVE
```
