### ISSUE TITLE
accessing the console via ingress

### ISSUE THREAD

**Issue by altfatterz** [infinispan/infinispan-helm-charts#87]
I would like to access the console via an ingress. I have decided not to use the `expose` part in the chart since currently there is no `tls` support in there.  With port forward everything seems to be ok, I can access the console. 

Do you know what am I doing wrong with the ingress setup?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svc-mb-infinispan
  annotations:
    meta.helm.sh/release-name: svc-mb-infinispan
    meta.helm.sh/release-namespace: foo
    "cert-manager.io/cluster-issuer": "letsencrypt"
    "kubernetes.io/ingress.class": "internal"
    "kubernetes.io/tls-acme": "true"
  labels:
    app: infinispan-ingress
    clusterName: svc-mb-infinispan
    helm.sh/chart: infinispan-0.3.2
    meta.helm.sh/release-name: svc-mb-infinispan
    meta.helm.sh/release-namespace: foo
    app.kubernetes.io/version: "14.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-mb-infinispan
                port:
                  number: 11222
      host: "mb-infinispan.intra.mimacom.io"
  tls:
    - hosts:
        - "mb-infinispan.intra.mimacom.io"
      secretName: mb-infinispan.intra.mimacom.io-tls
```

For some reason it does not work 

<img width="1730" alt="Screenshot 2023-09-19 at 14 43 17" src="https://github.com/infinispan/infinispan-helm-charts/assets/1025546/4a0112d9-e0b7-469e-a1cb-a34b7bd4bf62">

Here is the values file:

```bash
images:
  server: quay.io/infinispan/server:14.0
  initContainer: registry.access.redhat.com/ubi8-micro
deploy:
  replicas: 3
  container:
    storage:
      ephemeral: true
  infinispan:
    cacheContainer:
      statistics: true # Global statistics
      distributedCacheConfiguration:
        name: default
        mode: ASYNC
        statistics: true # Cache statistics
        encoding:
          mediaType: "application/x-java-serialized-object"
        expiration:
          lifespan: 300000
          maxIdle: 120000
        memory:
          maxCount: 1000
          whenFull: REMOVE
```
