### ISSUE TITLE
Add affinity to template

### ISSUE THREAD

**Issue by oburd** [infinispan/infinispan-helm-charts#89]
Hello!
Can you create affinity template for deployment ?
Because i don need hostname, i need zones
Is this possible ?
Thank you

**Comment by ryanemerson** [comment]
That's not currently possible. PRs are welcome though :slightly_smiling_face:

We could add `deploy.affinity` to the `values.yaml` and make it so the default value is what's currently specified in the template, e.g. values.yaml would look like:

```yaml
deploy:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                clusterName: {{ include "infinispan-helm-charts.name" . }}
                app: infinispan-pod
            topologyKey: kubernetes.io/hostname
          weight: 100
```
