### ISSUE TITLE
Console error after deploy default

### ISSUE THREAD

**Issue by oburd** [infinispan/infinispan-helm-charts#94]
Hello!
I have written issue there is a link:
https://github.com/infinispan/infinispan-helm-charts/issues/93

Shoud i change some thing here ?
As i understand this is default realm ?
```yaml  
infinispan:
    cacheContainer:
      # [USER] Add cache, template, and counter configuration.
      name: default
      # [USER] Specify `security: null` to disable security authorization.
      security:
        authorization: {}
```
